# Дополнительные подсказки: http://about.travis-ci.org/docs/user/languages/php/
language: php

# Введите любую версию PHP, которую вы хотите протестировать
php:
  - 5.4  # недавняя версия 5.4.x
  - 5.5  # недавняя версия 5.5.x
  - 5.6  # недавняя версия 5.6.x
  - 7.0  # недавняя версия 7.x
  - hhvm # недавняя версия hhvm

# (Необязательно) Cписок сред, например, для тестирования различных СУБД
env:
  - DB=mysql
  - DB=pgsql

# (Необязательно) Установить исключения и разрешенные ошибки в матрице
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
  exclude:
    - php: hhvm
      env: DB=pgsql # PDO драйвер для pgsql не поддерживается HHVM 
  allow_failures:
    - php: 7.0
    - php: hhvm

# Выполнять любое количество скриптов перед тестовым прогоном, пользовательские env доступны как переменные
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# Используйте переменную env $DB, чтобы определить phpunit.xml для использования
script: phpunit --configuration phpunit_$DB.xml --coverage-text

# Настроить уведомления (электронная почта, IRC и т. д.)
notifications:
  email: "gamervladok@gmail.com"
